import type { SiteProfile } from '../siteProfile';

export const smartProfile: SiteProfile = {
  id: 'smart',
  baseUrl: 'https://smart.md',
  routes: {
    home: '/',
    contact: '/contact',
    privacy: '/privacy-policy',
    cookies: '/cookie-policy',
    terms: '/terms-and-conditions',
    returns: '/return-policy',
    // NOTE: /catalog is more of an entry point and may not render product prices until a category is opened.
    // Use a concrete category listing to reliably detect price currency (lei).
    listing: '/smartphone?homepage_count',
    product: '/product',
    cart: '/cart',
    checkout: '/checkout',
  },
  applicability: {
    hasCheckout: true,
    redirectsToPartners: true,
    requiresLoginForCheckout: false,
  },
  i18n: {
    cookieAccept: ['Accept', 'Acceptă', 'Accepta', 'Sunt de acord', 'OK', 'Allow all', 'Принять', 'Согласен'],
    cookieReject: [
      'Reject',
      'Reject all',
      'Decline',
      'Decline all',
      'Respinge',
      'Respinge tot',
      'Refuz',
      'Refuză',
      'Nu accept',
      'Doar necesare',
      'Doar esențiale',
      'Doar esentiale',
      'Only necessary',
      'Only essential',
      'Отклонить',
      'Отказаться',
      'Только необходимые',
      'Только обязательные',
    ],
    cookieManage: [
      'Manage',
      'Manage cookies',
      'Customize',
      'Preferences',
      'Cookie settings',
      'Gestionează',
      'Gestioneaza',
      'Preferințe',
      'Preferinte',
      'Setări',
      'Setari',
      'Setări cookie',
      'Setari cookie',
      'Ajustează',
      'Ajusteaza',
      'Настроить',
      'Настройки',
      'Настройки cookie',
      'Настройки файлов cookie',
    ],
    termsCheckboxLabels: ['Termeni', 'Condiții', 'Conditii', 'T&C', 'Terms', 'условия'],
    finalizeOrderButtonLabels: [
      'Comandă cu obligația de plată',
      'Comanda cu obligatia de plata',
      'Plasează comanda',
      'Plaseaza comanda',
      'Finalizează comanda',
      'Finalizeaza comanda',
      'Place order',
      'Оплатить',
    ],
  },
  selectors: {
    cookieBannerRoot: [
      '#onetrust-consent-sdk',
      '#CybotCookiebotDialog',
      '[id*="consent" i]',
      '[class*="consent" i]',
      '[id*="cookie"]',
      '[class*="cookie"]',
      '[data-testid*="cookie"]',
      '[data-test*="cookie"]',
    ],
    checkoutTermsCheckbox: ['input[type="checkbox"][name*="terms" i]', 'input[type="checkbox"][id*="terms" i]'],
    checkoutFinalizeButton: ['button[type="submit"]', '[role="button"]'],
    linkAllAnchors: 'a[href]',

    // Currency checks must wait for catalog products to load (otherwise screenshot may capture skeleton placeholders).
    currencyTextRoot: ['#custom_products_content'],
    currencyReadySelector: [
      '#custom_products_content :text-matches("lei", "i")',
    ],
  },
  elementVisibilityById: {
    // Example mapping for element_visibility checks; extend per site as needed.
    // '2.6': { route: 'checkout', selectors: ['text=/livrare/i'] },
  },
};
